# Generated by Django 5.1.1 on 2024-12-24 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telegram_id', models.CharField(max_length=64, unique=True, verbose_name='Telegram User ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('role', models.CharField(choices=[('boss', 'Boss'), ('admin', 'Admin'), ('user', 'Regular User')], default='user', max_length=10, verbose_name='User Role')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('content', models.CharField(max_length=2048, verbose_name='Post Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Post Status')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='bott.user', verbose_name='Author')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
